package de.goldendeveloper.screenclient;

import com.sshtools.common.publickey.SshKeyPairGenerator;
import com.sshtools.common.publickey.SshKeyUtils;
import com.sshtools.common.ssh.SshException;
import com.sshtools.common.ssh.components.SshKeyPair;

import java.io.File;
import java.io.IOException;

public class SSH {

    public SSH() throws IOException, SshException {
        SshKeyPair pair = SshKeyPairGenerator.generateKeyPair(SshKeyPairGenerator.ED25519);
        SshKeyUtils.createPrivateKeyFile(pair, "my passphrase", new File(System.getProperty("user.home"), ".ssh/ssh_ed25555555555555555519"));
        SshKeyUtils.createPublicKeyFile(pair.getPublicKey(), "Generated by Maverick Synergy", new File(System.getProperty("user.home"), ".ssh/ssh_ed25555555555555555519.pub"));

    }
}
